### ISSUE TITLE
converts avi to bmp but cannot open 

### ISSUE THREAD

**Issue by bigflyingpotato** [borge-holme/celltraxx_download#1]
When running the 2_Wound-healing_PC-3_cells avi file through the imagej macro, it will detect this avi file in my C:\celltrax_data\ folder and begin to convert to bitmaps, but once it finishes writing the last image, an opener pop up appears indicating:

Unsupported format or file not found:
C:/celltraxx_data/2_Wound-healing_PC-3_cells_0000.bmp

I have confirmed that this bmp file has been created in C:\celltraxx_data\ and also made sure that the default settings were updated to match this avi. The last thing in the log window reads:

No flat field correction for video 2_Wound-healing_PC-3_cells.avi
Generating tuning image from bitmap 2_Wound-healing_PC-3_cells_0000.bmp.

Is this occurring because the program isn't reading the newly created bmp? This also occurred when running the Random migration of HeLa example video. I have tried the alternative celltrax versions, as well as updated my Microsoft Visual C++ Redistributable to the current version. I have also attempted to use one of my own wound healing avi files and get an error that there are no avi files in the folder. Any insight appreciated, I'm really interested in getting this up and running for analyses.

**Comment by borge-holme** [comment]
Thank you for the feedback! Seems like you have done all the right things, so strange that you get that error message. Based on the last log entry, please check if you have a folder called "tuning_temp" in your celltraxx_system directory (C:\celltraxx_system\tuning_temp). The folder is supposed to be generated automatically if missing, but this may not always happen, depending on the access settings. It may also help to run as administrator. Let me know if it still doesn't work.

**Comment by bigflyingpotato** [comment]
Thanks for the speedy response, it's strange indeed! 

At this point, I do have the tuning_temp folder in my system directory, and it does have .xlsx files generated in for the overall summary and individual data measures (position, track etc.), though understandably these are empty.

When I try an run as an admin, I get a system error:
The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem. 

I've reinstalled the redistributable with no success.

**Comment by borge-holme** [comment]
Thanks for the update! You may have already done it, but if not you could try to download the msvcr100.dll we have put in the folder
/celltraxx_download/alternative_celltraxx_versions/
You find more info in the accompanying ReadMe file in the same folder. This might help in case your dll for some reason is too old, even if you have reinstalled the redistributable. Let me know if this helps.

**Comment by bigflyingpotato** [comment]
Ah yes, I saw that earlier, though unfortunately, pulling the .dll into the system directory didn't help. I did go ahead and install the x86 version for both the older 2010 Redistributable and the current 2015-2022 version, but that still doesn't resolve the issue.

Currently even with the .dll copied over when I try to run through ImageJ, it still goes through the writing process, but comes up with the same error for not locating the initial bmp file, and when I run as admin I don't see it initiating the writing process at all. 

When I click on the .dll file and try to open in ImageJ, it gives me: File is not in a supported format, a reader plugin is not available or it was not found

Still scratching my head over this, grateful for your patience!

**Comment by borge-holme** [comment]
Thanks for trying out all those different options. Sorry to hear it still doesn't work. I don't have any good suggestions at the moment, but in such cases it may help to meet on Teams and troubleshoot together. How about you send me an e-mail to borge.holme[at]online.no so we can arrange a meeting?

**Comment by bigflyingpotato** [comment]
Sounds like a good plan, I'll connect with you shortly over email. Thank you for being so responsive and willing to help!
